### ISSUE TITLE
Медленная загрузка сайта

### ISSUE THREAD

**Issue by deviatovae** [Elijah-I/RS-clone#24]
Запросы за данными уходят последовательно. Из-за чего следующий запрос запускается только после выполнения предыдущего. Это приводит к многократному замедлению загрузки сайта.

Текущее поведение: 
- Запросы за данными уходят последовательно

Ожидаемое поведение:
- Запросы уходят параллельно, сайт открывается после окончания последнего (самого медленного) запроса

**Comment by Elijah-I** [comment]
Спасибо, что заметили, да, действительно надо было распараллелить запросы!
