### ISSUE TITLE
404 при попытке открыть ссылку страниц питания/тренировок

### ISSUE THREAD

**Issue by deviatovae** [Elijah-I/RS-clone#25]
1. Зайти на задеплоенный сайт - https://elijah-i.github.io/RS-clone/
1. Перейти на страницу питания или тренировки
1. Обновить страницу

Текущее поведение:
- Открылась белая пустая страница 

Ожидаемое поведение:
- Открылась та же самая страница (питания или тренировки)

Примечание:
Скорее всего проблема в отсутствии редиректа. См. https://stackoverflow.com/a/59677657

**Comment by Elijah-I** [comment]
Спасибо, что сообщили об ошибке! Поправили.
